### ISSUE TITLE
Chapter 02:  do_clear_done method throws error with @api.model

### ISSUE THREAD

**Issue by mkanderson** [PacktPublishing/Odoo-10-Development-Essentials#1]
Just started working through the book. Got this error when trying out the code from Chapter 02:

`Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 662, in call_kw_model
    recs = self.with_context(context or {})
  File "/opt/odoo/lib/odoo/odoo/models.py", line 4989, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
TypeError: cannot convert dictionary update sequence element #0 to a sequence`

To reproduce: 
* check out code, place in /mnt/extra-addons
* restart server, install module
* create a few tasks, mark some as done
* click on "Clear All Done"
* enjoy verbose Python trace ;-)

Testing with current Community Edition Docker image odoo:10 from Docker Hub.

Works fine if I remove the @api.model decorator from the method do_clear_done.

**Comment by thangduong3010** [comment]
Thanks @mkanderson  :)
Looking forward to official fix

**Comment by farraez-sinapsys-global** [comment]
## The original code is:

```
    @api.model
    def do_clear_done(self):
        dones = self.search([('is_done', '=', True)])
        dones.write({'active': False})
        return True   
```

So, I change the method decorator, by **@api.multi** and then it worked. 

```
    @api.multi
    def do_clear_done(self):
        dones = self.search([('is_done', '=', True)])
        dones.write({'active': False})
        return True
```

**Comment by MackZhong** [comment]
```
    @api.model
    def do_clear_done(self, ids):
```
it works.
